version: '3'
services:
  web1:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    environment:
      - PORT=8081
    volumes:
      - ./angular_app/dist/angular_app/browser:/usr/share/nginx/html
      - ./scripts/entrypoint.sh:/docker-entrypoint.d/10-envsubst.sh
    ports:
      - 8081:80

  web2:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    environment:
      - PORT=8082
    volumes:
      - ./angular_app/dist/angular_app/browser:/usr/share/nginx/html
      - ./scripts/entrypoint.sh:/docker-entrypoint.d/10-envsubst.sh
    ports:
      - 8082:80

  web3:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    environment:
      - PORT=8083
    volumes:
      - ./angular_app/dist/angular_app/browser:/usr/share/nginx/html
      - ./scripts/entrypoint.sh:/docker-entrypoint.d/10-envsubst.sh
    ports:
      - 8083:80

  haproxy:
    image: haproxy:alpine
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
      - web3
